---
# Set AWS profile
#profile: dev

# Set AWS region
aws_region: us-east-1

name: "cetral-vpc"
cidr: "172.0.0.0/20"
azs: ["us-east-1a", "us-east-1b", "us-east-1c"]
private_subnets: ["172.0.1.0/24", "172.0.2.0/24", "172.0.3.0/24"]
public_subnets: ["172.0.4.0/24", "172.0.5.0/24", "172.0.6.0/24"]

mandate_tags: ["Product" : "plt","InfraOwner" : "sre-cloud-reliability@tavisca.com","DataClassification" : "internal"]



